### ISSUE TITLE
Receiving two warnings when loading in Expo SDK 35

### ISSUE THREAD

**Issue by pdugan20** [alexZajac/react-native-skeleton-content#3]
I'm getting the following warnings:
Warning: Invalid argument supplied to oneOfType. Expected an array of check functions
, but received string at index 0.

Warning: Each child in a list should have a unique "key" prop.%s%s See https://fb.me/
react-warning-keys for more information.%s,

Stack traces are below.

Warning: Invalid argument supplied to oneOfType. Expected an array of check functions
, but received string at index 0.
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/prop-types/factoryWithTypeCheckers.js:23:20 in printWarning
- node_modules/prop-types/factoryWithTypeCheckers.js:373:10 in createUnionTypeChecker
- node_modules/react-native-skeleton-content/src/Skeleton/SkeletonContent.js:276:30 i
n <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-native-skeleton-content/src/Skeleton/index.js:1:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-native-skeleton-content/src/index.js:1:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* screens/ProfileScreen.js:6:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* screens/Index.js:6:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* navigator/TabNavigator.js:7:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* navigator/AppNavigator.js:2:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* App.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:197:45 in guardedLoadModule
* null:null in global code

Warning: Each child in a list should have a unique "key" prop.%s%s See https://fb.me/
react-warning-keys for more information.%s,

Check the render method of `SkeletonContent`., ,
    in View (at SkeletonContent.js:199)
    in SkeletonContent (at ProfileScreen.js:60)
    in RCTView (at View.js:45)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at ProfileScreen.js:129)
    in ProfileScreen (created by Context.Consumer)
    in Connect(ProfileScreen) (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:909)
    in RCTView (at View.js:45)
 in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:984)
    in RCTView (at View.js:45)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:393)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:383)
in PanGestureHandler (at StackViewLayout.tsx:376)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:45)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at SceneView.js:9)
    in SceneView (at createTabNavigator.tsx:67)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.tsx:42)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.tsx:26)
in ResourceSavingScene (at createBottomTabNavigator.tsx:157)
    in RCTView (at View.js:45)
    in View (at screens.native.js:101)
    in ScreenContainer (at createBottomTabNavigator.tsx:147)
    in RCTView (at View.js:45)
    in View (at createBottomTabNavigator.tsx:146)
    in TabNavigationView (at createTabNavigator.tsx:228)
    in NavigationView (at createNavigator.js:80)
    in Navigator (at createAppContainer.js:430)
    in NavigationContainer (at App.js:10)
    in Provider (at App.js:9)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- ... 23 more stack frames from framework internals

**Comment by alexZajac** [comment]
Hi! 
I'm trying to integrate the package with Jest and Enzyme right now and I'll make sure those warnings don't come up in the next versions!

**Comment by alexZajac** [comment]
Hi @pdugan20 ! 
This should now be solved with the latest release, can you check ?

**Comment by appsgenie** [comment]
Hi,
I am still getting this: Each child in a list should have a unique "key" prop.
My setup is simple. No content inside the <SkeletonContent /> component. Just using the layout property to supply placeholders.
Any ideas if there is a way to pass keys down to it?

**Comment by alexZajac** [comment]
Hey @appseugene, I realeased the 1.0.12 version to take care of the warning!
