### ISSUE TITLE
Tried to register two views with the same name ViewManagerAdapter_ExpoLinearGradient

### ISSUE THREAD

**Issue by vrinch** [alexZajac/react-native-skeleton-content#8]
thanks for this package, I am trying to use the package but I am getting an error of Tried to register two views with the same name ViewManagerAdapter_ExpoLinearGradient. I think its probably because I have Expo-Linear-Gradient version 6.0.0 installed (I am using Expo SDK 34.0.0). I checked the package in node modules and saw it had a Expo-Linear-Gradient version 7.0.1 in the dependencies. How can I go about this please. Thanks

**Comment by bsor-dev** [comment]
Same

**Comment by ryoid** [comment]
Also experiencing this with expo-linear-gradient 8.0.0 and expo 36.0.0

**Comment by alexZajac** [comment]
I updated the version of expo-linear-gradient and it should be working now. 
Keep mu updated if anything pops up!

**Comment by Kleinhummel** [comment]
Still experiencing this with expo 36.0.0 and expo-linear-gradient 8.0.0

**Comment by appsgenie** [comment]
same here with sdk 36.0.0 and expo-linear-gradient 8.0.0

**Comment by wdonray** [comment]
@appseugene and @Kleinhummel I fixed it by make sure its typed like this  "expo-linear-gradient": "^8.0.0", and not  "expo-linear-gradient": "~8.0.0". This fixed the issue for me.

**Comment by nandorojo** [comment]
@wdonray that did it for me too, thanks!

**Comment by Joshandrews43** [comment]
This came back for me with the SDK 40 update. Any ideas? Please update to `expo-linear-gradient: 8.4.0`

**Comment by wobsoriano** [comment]
I had to switch to another skeleton loader since the last update here was August.

Found this one: https://github.com/mfrachet/rn-placeholder

It's also typed

**Comment by appsgenie** [comment]
Same here with an upgrade to SDK 40.. I ahve `"expo-linear-gradient": "~8.4.0"` install and not sure which version to use now. I installed 8.0.0 and still having the error...

**Comment by jkulker** [comment]
same problem here aswell can it be reopened!

**Comment by Egi-B** [comment]
by changing to ^8.4.0 I started getting:
![image](https://user-images.githubusercontent.com/15939884/108505261-642a2f80-72b7-11eb-886f-8eec6ae1fe9b.png)

**Comment by tomiito** [comment]
I had the same error, I downgraded to version `8.0.0` and make sure that my internal private libraries that was using that one as well, were using `8.0.0` and works! 

This error happens when a duplicate library is found caused by version mismatch. 

Example of my node_modules 
expo-linear-gradient@8.0.0 <-- imported by my package.json
node_modules/@mydomain/mylibrary 
                                      -> node_modules -> expo-linear-gradient@8.4.0 <--badly imported by my dependency using ^8.0.0
                                      
Solved by cleaning the folders and reinstalling.

**Comment by AKclown** [comment]
I had the same error,
`
   "expo": "^41.0.0",
   "expo-linear-gradient":"~9.1.0"
`

**Comment by lexlemmens** [comment]
@AKclown Same, did you find a solution?

**Comment by nicobermudez** [comment]
Having the same issue with Expo 41.0.0 and expo-linear-gradient 9.1.0 as well. Prefer not to downgrade these, any suggestions?

**Comment by gregdburns** [comment]
We also had the issue and had to downgrade to version 8.4.0 in the meantime, which works fine.  I tried [npm-force-resolutios](https://github.com/rogeriochaves/npm-force-resolutions) with no luck.

Created a new issue for this, rather than commenting in a previous closed issue related to past upgrades.  https://github.com/alexZajac/react-native-skeleton-content/issues/43

**Comment by nightness** [comment]
Since people continue to report this, I almost did but realized why... I ejected for fun and was playing around with Android Studio. Long story short, I ended up messing up my environment variables via .bashrc and adding an incorrect value for ANDROID_AVD_HOME.

**Comment by raufabr** [comment]
This was resolved for me after I uninstalled react-native-linear-gradient library from my project.

**Comment by luizwhite** [comment]
This worked for me for SDK 42:

(package.json)

  "resolutions": {
    "expo-linear-gradient": "~9.2.0"
  },

**Comment by raphaeltm** [comment]
Thanks for the hint @luizwhite 

I was having the same problem with Expo SDK 44. Fixed with

```
"resolutions": {
    "expo-linear-gradient": "~11.0.0"
  },
```

**Comment by DavidAPears** [comment]
Thanks @raphaeltm - worked for me 🤘🏻

**Comment by amisoliman** [comment]
> "resolutions": {
>     "expo-linear-gradient": "~11.0.0"
>   },

I added this resolutions to the package.json as below but for some reasons didn't work. Is there anything i'm missing?

{
  "name": "bolierplate",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/datetimepicker": "^6.1.3",
    "@react-native-community/netinfo": "7.1.3",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "6.1.3",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.2",
    "@react-navigation/stack": "^6.2.1",
    "ad-b2c-react-native": "^2.0.0",
    "axios": "^0.26.1",
    "dotenv": "^16.0.0",
    "expo": "~44.0.0",
    "expo-analytics": "^1.0.18",
    "expo-app-loading": "^1.3.0",
    "expo-av": "~10.2.0",
    "expo-constants": "^13.1.1",
    "expo-device": "~4.1.0",
    "expo-facebook": "~12.1.0",
    "expo-fast-image": "^1.1.3",
    "expo-file-system": "~13.1.4",
    "expo-firebase-analytics": "^7.0.0",
    "expo-font": "^10.0.5",
    "expo-linear-gradient": "~11.0.3",
    "expo-linking": "~3.0.0",
    "expo-modules-core": "0.6.5",
    "expo-navigation-bar": "~1.1.1",
    "expo-notifications": "^0.15.2",
    "expo-permissions": "^13.2.0",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "~0.11.7",
    "expo-web-browser": "~10.1.0",
    "firebase": "9.6.10",
    "formik": "^2.2.9",
    "moment": "^2.29.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-animatable": "^1.3.3",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-appearance": "^0.3.4",
    "react-native-bouncy-checkbox": "^2.1.10",
    "react-native-chart-kit": "^6.12.0",
    "react-native-expo-cached-image": "^1.3.1",
    "react-native-floating-action": "^1.22.0",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-i18n": "1.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-progress": "^5.0.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-select-dropdown": "^2.0.3",
    "react-native-shared-element": "0.8.3",
    "react-native-skeleton-content": "^1.0.24",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.1.1",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-timeline-flatlist": "^0.8.0",
    "react-native-toast-message": "^2.1.5",
    "react-native-web": "0.17.1",
    "react-native-webview": "^11.22.3",
    "react-navigation-shared-element": "^3.1.3",
    "yup": "^0.32.11"
  },
  "resolutions": {
    "expo-linear-gradient": "~11.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@expo/webpack-config": "^0.16.24",
    "babel-loader": "^8.2.5"
  },
  "private": true
}

**Comment by micksmits** [comment]
@amisoliman Try running `npm dedupe`. I had the same issue and it seems I had the same extension installed twice. Not sure how this happens exactly.
